DOMAIN=softfluid.fr
PLTF_NAME=SoftFluid AI

# Secondary domains (comma-separated list)
# Format: "domain1:server_names:proxy_pass,domain2:server_names:proxy_pass"
# Example: "hypervisia.fr:hypervisia.fr www.hypervisia.fr:https://softfluid.fr:6137"
SECONDARY_DOMAINS=hypervisia.fr:hypervisia.fr www.hypervisia.fr:https://softfluid.fr:6137
