DOMAIN=opcp-psmc.fr
PLTF_NAME=opcp-psmc AI

# Secondary domains (comma-separated list)
# Format: "domain1:server_names:proxy_pass,domain2:server_names:proxy_pass"
# Example: "opcp-psmc.fr:opcp-psmc.fr www.opcp-psmc.fr:https://opcp-psmc.fr:6137"
SECONDARY_DOMAINS=opcp-psmc.fr:opcp-psmc.fr www.opcp-psmc.fr:https://opcp-psmc.fr:6137
