DOMAIN=opcp-psmc.com
PLTF_NAME=opcp-psmc AI

# Secondary domains (comma-separated list)
# Format: "domain1:server_names:proxy_pass,domain2:server_names:proxy_pass"
# Example: "opcp-psmc.com:opcp-psmc.com www.opcp-psmc.com:https://opcp-psmc.com:6137"
SECONDARY_DOMAINS=
